name: build-tag


on:
  push:
    branches:
      - v*

jobs:
  build:
    container: tarscloud/base-compiler
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.tarsyun.com
          username: ${{ secrets.name }}
          password: ${{ secrets.pass }}
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: make
        run: mkdir -p build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release && make -j4
      - name: build docker
        run: |
          exec-build-cloud.sh tarscloud/tars.cppbase cpp build/bin/AdminServer yaml/admin-values.yaml ${{ steps.get_version.outputs.VERSION }} true
          exec-build-cloud.sh tarscloud/tars.cppbase cpp build/bin/NodeServer yaml/node-values.yaml ${{ steps.get_version.outputs.VERSION }} true